### ISSUE TITLE
 No repository for "XXXRepository" was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by freefred81** [IRCraziestTaxi/typeorm-linq-repository#70]
Hi ... I'm trying to use TypeORM-Linq with my Nest.js project. 
But it give to me this error on startup:

> [Nest] 1208   - 2019-08-22 9:07 AM   [ExceptionHandler] No repository for "OpportunityRepository" was found. Looks like this entity is not registered in current "default" connection? +32ms
RepositoryNotFoundError: No repository for "OpportunityRepository" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/Users/fscamuzzi/Documents/Temp/nestproject/src/error/RepositoryNotFoundError.ts:10:9)
    at EntityManager.getRepository (/Users/fscamuzzi/Documents/Temp/nestproject/src/entity-manager/EntityManager.ts:1008:19)
    at Connection.getRepository (/Users/fscamuzzi/Documents/Temp/nestproject/src/connection/Connection.ts:342:29)
    at getRepository (/Users/fscamuzzi/Documents/Temp/nestproject/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:13:26)
    at InstanceWrapper.useFactory [as metatype] (/Users/fscamuzzi/Documents/Temp/nestproject/node_modules/@nestjs/typeorm/dist/typeorm.providers.js:22:20)
    at Injector.instantiateClass (/Users/fscamuzzi/Documents/Temp/nestproject/node_modules/@nestjs/core/injector/injector.js:279:55)
    at callback (/Users/fscamuzzi/Documents/Temp/nestproject/node_modules/@nestjs/core/injector/injector.js:74:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Waiting for the debugger to disconnect...

If i remove TypeOrm-linq everything works as expected ...

Can you help me? your prject for a guy like me who came from a strong C# background is a Joy!!! ...

my repo :

https://github.com/freefred81/nestproject

**Comment by freefred81** [comment]
I have change a little bit my code ..and now it works .. BUT only the GetAll() ... if i try a where clause it stay stucked .. if you ping me i'll update the repo ... thnx!

**Comment by freefred81** [comment]
Hi .. any news?

**Comment by IRCraziestTaxi** [comment]
Sorry I have been off the radar. Work has been bonkers lately.

I will take a look at the repo and see if I can spot the problem.

**Comment by IRCraziestTaxi** [comment]
@freefred81 Your usage of

```ts
let query =  await this.opportunityRepository.getAll()
    .where(xx => xx.isdeleted)
    .isFalse();
```

looks correct. Could you clarify what you mean by

> if i try a where clause it stay stucked

? Do you get an error or does the async never return? Hopefully you can get that info to me quicker than it would take me to get a database set up and all that so I can try it myself.

**Comment by freefred81** [comment]
Hi ...!!! ... First of all REALLY REALLY thnx for your time and support .... !! .. i know you maybe work hard .. so really thnx for your time !! ... I'vee update my repo with a new folder (database) inside there's a scripts folder where you can find 2 scripts (.sql) to create the Table Opportunity e insert one record inside it ... So you can debug it and you'll se what happen .... if you try to a 



> http://localhost:3000/opportunity

it  hit the method in the controller

```
 @Get()
  async findAll(@Query() query: QueryParams): Promise<OpportunityDto[]> {
    const resultEntities = await this.opportunityService.getAll();
    return resultEntities;
  }

```
It calls the getAll() method in the opportunityService:


>  getAll = async (): Promise<OpportunityDto[]> => {
> 
>     const result = await this.opportunityRepository.getAll();
>     return result.map(xx => xx.ToDto());
> 
>   };


and it call the getAll() method from the OpportunityRepository (which extends your LinqRepository)

```
@Injectable()
// @EntityRepository(Opportunity)
export class OpportunityRepository extends LinqRepository<Opportunity> implements IOpportunityRepository {

    public constructor() {
        super(Opportunity);
    }

}
```


Here everything works as expected ...

but if you try to call other API in of the OpportunityController with

> http://localhost:3000/opportunity/not/deleted?skip=0&take=10

it call the method of controller


```
  @Get('not/deleted')
  async findAllNotDeleted(@Query() query: QueryParams): Promise<OpportunityDto[]> {
    const resultEntities = await this.opportunityService.findNotDeleted(query);
    return resultEntities;
  }
```


 it calls the findNotDeleted(..) method in the opportunityService

```
 findNotDeleted = async (params: QueryParams): Promise<OpportunityDto[]> => {

    let query = this.opportunityRepository.getAll()
      .where(xx => xx.isdeleted)
      .isFalse();

    const countNotDeleted = await query.count();

    // Set paging parameters on the query.
    query =  query
      .skip(params.skip)
      .take(params.tale);

    const result = await query;
    return result.map(xx => xx.ToDto());

  }
```

BUT here when it reach  the ` let query = this.opportunityRepository.getAll()
      .where(xx => xx.isdeleted)
      .isFalse();
` in the debug tab (see screenshot above of my vscode debug tab) it hit the DB with a FULL select * frorm Opportunityt (no where ) and it's also strange cause it launch the query BEFORE the await  ... and another strange things .. even if it launch the wrong query (and it's logged in the debug tab) .. it get stuck and NO RESULT IS RETURNED ...

![image](https://user-images.githubusercontent.com/25612263/63640096-a2339c80-c69c-11e9-8dde-196ba83182b5.png)

**Comment by IRCraziestTaxi** [comment]
How are you debugging? Can you share your `launch.json`? I haven't really used nest or nodemon and am having quite a time trying to figure out how to debug with it.

**Comment by freefred81** [comment]
Really sorry for delay ...

try to install nodemon globally with

`npm install -g nodemon`

then inside the project (once you've 

> open it with vs code try the auto attach settings and sei it to ON

> then strat the npm scipts start:debug

Vs code will start in debug mode (and will hitting yours break point)



![image](https://user-images.githubusercontent.com/25612263/63670221-6869af80-c7dc-11e9-9099-7a26045381a8.png)

**Comment by freefred81** [comment]
mmm looks strange .. i don'n have any error..  try to disable the tslint vscode extensions (it's too much strict).

> then have you set auto attach to ON in the vscode?

**Comment by freefred81** [comment]
Hi !! ... IT WORKS!!!!! .... really really thnx for your time and patiente ... it works as expected!! .... you' re the number ONE!!!
